# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := tfjs_binding
DEFS_Debug := \
	'-DNODE_GYP_MODULE_NAME=tfjs_binding' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DBUILDING_NODE_EXTENSION' \
	'-DDEBUG' \
	'-D_DEBUG' \
	'-DV8_ENABLE_CHECKS'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-g \
	-O0

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-exceptions \
	-std=gnu++1y

INCS_Debug := \
	-I/usr/local/google/home/kangyizhang/.node-gyp/10.15.3/include/node \
	-I/usr/local/google/home/kangyizhang/.node-gyp/10.15.3/src \
	-I/usr/local/google/home/kangyizhang/.node-gyp/10.15.3/deps/openssl/config \
	-I/usr/local/google/home/kangyizhang/.node-gyp/10.15.3/deps/openssl/openssl/include \
	-I/usr/local/google/home/kangyizhang/.node-gyp/10.15.3/deps/uv/include \
	-I/usr/local/google/home/kangyizhang/.node-gyp/10.15.3/deps/zlib \
	-I/usr/local/google/home/kangyizhang/.node-gyp/10.15.3/deps/v8/include \
	-I$(srcdir)/.. \
	-I/usr/local/google/home/kangyizhang/tensorflow/tfjs-node/deps/include

DEFS_Release := \
	'-DNODE_GYP_MODULE_NAME=tfjs_binding' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DBUILDING_NODE_EXTENSION'

# Flags passed to all source files.
CFLAGS_Release := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-O3 \
	-fno-omit-frame-pointer

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-exceptions \
	-std=gnu++1y

INCS_Release := \
	-I/usr/local/google/home/kangyizhang/.node-gyp/10.15.3/include/node \
	-I/usr/local/google/home/kangyizhang/.node-gyp/10.15.3/src \
	-I/usr/local/google/home/kangyizhang/.node-gyp/10.15.3/deps/openssl/config \
	-I/usr/local/google/home/kangyizhang/.node-gyp/10.15.3/deps/openssl/openssl/include \
	-I/usr/local/google/home/kangyizhang/.node-gyp/10.15.3/deps/uv/include \
	-I/usr/local/google/home/kangyizhang/.node-gyp/10.15.3/deps/zlib \
	-I/usr/local/google/home/kangyizhang/.node-gyp/10.15.3/deps/v8/include \
	-I$(srcdir)/.. \
	-I/usr/local/google/home/kangyizhang/tensorflow/tfjs-node/deps/include

OBJS := \
	$(obj).target/$(TARGET)/binding/tfjs_backend.o \
	$(obj).target/$(TARGET)/binding/tfjs_binding.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread \
	-rdynamic \
	-m64 \
	-L/usr/local/google/home/kangyizhang/tensorflow/tfjs-node/deps/lib

LDFLAGS_Release := \
	-pthread \
	-rdynamic \
	-m64 \
	-L/usr/local/google/home/kangyizhang/tensorflow/tfjs-node/deps/lib

LIBS := \
	-Wl,-rpath,\$$ORIGIN/../../deps/lib \
	-ltensorflow \
	-ltensorflow_framework

$(obj).target/tfjs_binding.node: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/tfjs_binding.node: LIBS := $(LIBS)
$(obj).target/tfjs_binding.node: TOOLSET := $(TOOLSET)
$(obj).target/tfjs_binding.node: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,solink_module)

all_deps += $(obj).target/tfjs_binding.node
# Add target alias
.PHONY: tfjs_binding
tfjs_binding: $(builddir)/tfjs_binding.node

# Copy this to the executable output path.
$(builddir)/tfjs_binding.node: TOOLSET := $(TOOLSET)
$(builddir)/tfjs_binding.node: $(obj).target/tfjs_binding.node FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/tfjs_binding.node
# Short alias for building this executable.
.PHONY: tfjs_binding.node
tfjs_binding.node: $(obj).target/tfjs_binding.node $(builddir)/tfjs_binding.node

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/tfjs_binding.node

