# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := tfjs_binding
### Rules for action "deps-stage":
quiet_cmd_binding_gyp_tfjs_binding_target_deps_stage = ACTION binding_gyp_tfjs_binding_target_deps_stage $@
cmd_binding_gyp_tfjs_binding_target_deps_stage = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd $(srcdir)/.; mkdir -p /usr/local/google/home/kangyizhang/test/node-pre/lib/binding/napi-v3; node /usr/local/google/home/kangyizhang/test/node-pre/scripts/deps-stage.js move /usr/local/google/home/kangyizhang/test/node-pre/lib/binding/napi-v3

/usr/local/google/home/kangyizhang/test/node-pre/lib/binding/napi-v3/libtensorflow.so: obj := $(abs_obj)
/usr/local/google/home/kangyizhang/test/node-pre/lib/binding/napi-v3/libtensorflow.so: builddir := $(abs_builddir)
/usr/local/google/home/kangyizhang/test/node-pre/lib/binding/napi-v3/libtensorflow.so: TOOLSET := $(TOOLSET)
/usr/local/google/home/kangyizhang/test/node-pre/lib/binding/napi-v3/libtensorflow.so: /usr/local/google/home/kangyizhang/test/node-pre/scripts/deps-stage.js FORCE_DO_CMD
	$(call do_cmd,binding_gyp_tfjs_binding_target_deps_stage)

all_deps += /usr/local/google/home/kangyizhang/test/node-pre/lib/binding/napi-v3/libtensorflow.so
action_binding_gyp_tfjs_binding_target_deps_stage_outputs := /usr/local/google/home/kangyizhang/test/node-pre/lib/binding/napi-v3/libtensorflow.so


DEFS_Debug := \
	'-DNODE_GYP_MODULE_NAME=tfjs_binding' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DBUILDING_NODE_EXTENSION' \
	'-DDEBUG' \
	'-D_DEBUG' \
	'-DV8_ENABLE_CHECKS'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-g \
	-O0

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-exceptions \
	-std=gnu++0x

INCS_Debug := \
	-I/usr/local/google/home/kangyizhang/.node-gyp/8.14.0/include/node \
	-I/usr/local/google/home/kangyizhang/.node-gyp/8.14.0/src \
	-I/usr/local/google/home/kangyizhang/.node-gyp/8.14.0/deps/openssl/config \
	-I/usr/local/google/home/kangyizhang/.node-gyp/8.14.0/deps/openssl/openssl/include \
	-I/usr/local/google/home/kangyizhang/.node-gyp/8.14.0/deps/uv/include \
	-I/usr/local/google/home/kangyizhang/.node-gyp/8.14.0/deps/zlib \
	-I/usr/local/google/home/kangyizhang/.node-gyp/8.14.0/deps/v8/include \
	-I$(srcdir)/.. \
	-I/usr/local/google/home/kangyizhang/test/node-pre/deps/include

DEFS_Release := \
	'-DNODE_GYP_MODULE_NAME=tfjs_binding' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DBUILDING_NODE_EXTENSION'

# Flags passed to all source files.
CFLAGS_Release := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-O3 \
	-fno-omit-frame-pointer

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-exceptions \
	-std=gnu++0x

INCS_Release := \
	-I/usr/local/google/home/kangyizhang/.node-gyp/8.14.0/include/node \
	-I/usr/local/google/home/kangyizhang/.node-gyp/8.14.0/src \
	-I/usr/local/google/home/kangyizhang/.node-gyp/8.14.0/deps/openssl/config \
	-I/usr/local/google/home/kangyizhang/.node-gyp/8.14.0/deps/openssl/openssl/include \
	-I/usr/local/google/home/kangyizhang/.node-gyp/8.14.0/deps/uv/include \
	-I/usr/local/google/home/kangyizhang/.node-gyp/8.14.0/deps/zlib \
	-I/usr/local/google/home/kangyizhang/.node-gyp/8.14.0/deps/v8/include \
	-I$(srcdir)/.. \
	-I/usr/local/google/home/kangyizhang/test/node-pre/deps/include

OBJS := \
	$(obj).target/$(TARGET)/binding/tfjs_backend.o \
	$(obj).target/$(TARGET)/binding/tfjs_binding.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our actions/rules run before any of us.
$(OBJS): | $(action_binding_gyp_tfjs_binding_target_deps_stage_outputs)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
# Build our special outputs first.
$(obj).target/tfjs_binding.node: | $(action_binding_gyp_tfjs_binding_target_deps_stage_outputs)

# Preserve order dependency of special output on deps.
$(action_binding_gyp_tfjs_binding_target_deps_stage_outputs): | 

LDFLAGS_Debug := \
	-pthread \
	-rdynamic \
	-m64 \
	-L/usr/local/google/home/kangyizhang/test/node-pre/lib/binding/napi-v3

LDFLAGS_Release := \
	-pthread \
	-rdynamic \
	-m64 \
	-L/usr/local/google/home/kangyizhang/test/node-pre/lib/binding/napi-v3

LIBS := \
	-Wl,-rpath,\$$ORIGIN \
	-ltensorflow \
	-ltensorflow_framework

$(obj).target/tfjs_binding.node: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/tfjs_binding.node: LIBS := $(LIBS)
$(obj).target/tfjs_binding.node: TOOLSET := $(TOOLSET)
$(obj).target/tfjs_binding.node: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,solink_module)

all_deps += $(obj).target/tfjs_binding.node
# Add target alias
.PHONY: tfjs_binding
tfjs_binding: $(builddir)/tfjs_binding.node

# Copy this to the executable output path.
$(builddir)/tfjs_binding.node: TOOLSET := $(TOOLSET)
$(builddir)/tfjs_binding.node: $(obj).target/tfjs_binding.node FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/tfjs_binding.node
# Short alias for building this executable.
.PHONY: tfjs_binding.node
tfjs_binding.node: $(obj).target/tfjs_binding.node $(builddir)/tfjs_binding.node

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/tfjs_binding.node

